apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-private-note-service
  labels:
    app: {{ .Release.Name }}-private-note
    role: server
    tier: backend
spec:
  selector:
    app: private-note
    role: server
    tier: backend
  ports:
    - name: private-note-port
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 8080