apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  labels:
    app: redis
    role: db
    tier: backend
spec:
  storageClassName: manual
  capacity:
    storage: 32Mi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Mi