apiVersion: v1
kind: Service
metadata:
  name: private-note-service
spec:
  selector:
    app: private-note
  ports:
    - name: private-note-port
      port: 80
      protocol: TCP
      targetPort: 8080