apiVersion: v1
kind: Service
metadata:
  name: private-note-service
  labels:
    app: private-note
    role: server
    tier: backend
spec:
  selector:
    app: private-note
    role: server
    tier: backend
  ports:
    - name: private-note-port
      port: 80
      protocol: TCP
      targetPort: 8080