apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-note-deployment
  labels:
    app: private-note
  creationTimestamp: null
spec:
  replicas: 2
  selector:
    matchLabels:
      app: private-note
  strategy: { }
  template:
    metadata:
      labels:
        app: private-note
      creationTimestamp: null
    spec:
      containers:
        - name: private-note
          image: arianboukani/private-note
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 100m
          volumeMounts:
            - mountPath: /app/config.json
              subPath: production-config.json
              name: config-map
      volumes:
        - name: config-map
          configMap:
            name: private-note-config
