apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    role: db
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: db
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
        role: db
        tier: backend
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: db_password
          volumeMounts:
            - name: redis-pv
              mountPath: /data/redis
      volumes:
        - name: redis-pv
          persistentVolumeClaim:
            claimName: redis-pvc