apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  serviceName: redis
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      initContainers:
        - name: init-redis
          image: redis:7.0.2-bullseye
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: redis-secret
          command:
            - bash
            - '-c'
            - |
              set -ex
              # Generate redis server-id from pod ordinal index
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              # Copy appropriate conf.d files from config-map to emptyDir
              if [[ $ordinal -eq 0 ]]; then
                cp /mnt/config-map/master.conf /etc/redis.conf
              else
                cp /mnt/config-map/slave.conf /etc/redis.conf
              fi
              echo "requirepass $(REDIS_PASSWORD)" >> /etc/redis.conf
              echo "masterauth $(REDIS_PASSWORD)" >> /etc/redis.conf
          volumeMounts:
            - name: conf
              mountPath: /etc/
              subPath: redis.conf
            - name: config-map
              mountPath: /mnt/config-map
      containers:
        - image: redis:7.0.2-bullseye
          name: redis
          command: [ "redis-server" ]
          args: [ "/etc/redis.conf" ]
          ports:
            - name: redis-port
              containerPort: 6379
          resources: {}
          volumeMounts:
            - name: conf
              mountPath: /etc/
              subPath: redis.conf
            - mountPath: /data
              name: data
      volumes:
        - name: config-map
          configMap:
            name: private-note-config
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          volume.alpha.kubernetes.io/storage-class: default
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Mi
    - metadata:
        name: conf
        annotations:
          volume.alpha.kubernetes.io/storage-class: default
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Mi